version: "2.1"

volumes:
  matlab:
    external: true

services:
  database:
    build: ./mongodb
    container_name: "mongodb"
    network_mode: "bridge"
    ports: 
      - "27017:27017"
    env_file:
      - ./mongodb/.env
      
  hrv-client:
    build: 
      context: ./hrv-client
      dockerfile: Dockerfile
    volumes:
      - ./hrv-client:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: "bridge"
    ports: 
      - "4500:4500" 
      
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: "bridge"
    ports: 
      - "4200:4200" 


  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    privileged: true
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - matlab:/usr/local/MATLAB
    environment:
      - NODE_ENV=production
    network_mode: "bridge"    
    ports: 
      - "3000:3000"
    links:
      - database:mongodb

  nginx:
    build: ./nginx
    network_mode: "bridge"
    ports:
      - "80:80"
    links:
      - client
      - server
      - hrv-client
