FROM node

RUN apt-get update

#-----------------------------------------------Install MATLAB------------------------------------------------
RUN apt-get install -y unzip

RUN mkdir /mcr-install && \    
    cd /mcr-install && \
    wget http://ssd.mathworks.com/supportfiles/downloads/R2015b/deployment_files/R2015b/installers/glnxa64/MCR_R2015b_glnxa64_installer.zip && \  
    mkdir /usr/local/MATLAB && \
    cd /mcr-install && \
    unzip -q MCR_R2015b_glnxa64_installer.zip && \
    ./install -destinationFolder /usr/local/MATLAB -agreeToLicense yes -mode silent && \
    cd / && \
    rm -rf mcr-install

ENV LD_LIBRARY_PATH /usr/local/MATLAB/v90/runtime/glnxa64:/usr/local/MATLAB/v90/bin/glnxa64

#-----------------------------------------Install PYTHON & SITE PACKAGES--------------------------------------
RUN apt-get install -y python3 \
    python \
    python3-pip

RUN pip3 install --upgrade pip

RUN pip3 install opencv-contrib-python

#--------------------------------------------------Install APP------------------------------------------------
RUN mkdir -p /usr/src/app

COPY ./package.json ./package-lock.json /usr/src/app/

WORKDIR /usr/src/app

RUN npm install

EXPOSE 3000

CMD docker build -t docker-sandbox sandbox/ && npm run watch
